// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/location_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionRequest) Reset() {
	*x = GetRegionRequest{}
	mi := &file_proto_location_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionRequest) ProtoMessage() {}

func (x *GetRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionRequest.ProtoReflect.Descriptor instead.
func (*GetRegionRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRegionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRegionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          int32                  `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort          *SortOptions           `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionsRequest) Reset() {
	*x = GetRegionsRequest{}
	mi := &file_proto_location_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionsRequest) ProtoMessage() {}

func (x *GetRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionsRequest.ProtoReflect.Descriptor instead.
func (*GetRegionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetRegionsRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetRegionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRegionsRequest) GetSort() *SortOptions {
	if x != nil {
		return x.Sort
	}
	return nil
}

type SearchRegionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Skip          int32                  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort          *SortOptions           `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRegionsRequest) Reset() {
	*x = SearchRegionsRequest{}
	mi := &file_proto_location_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRegionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRegionsRequest) ProtoMessage() {}

func (x *SearchRegionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRegionsRequest.ProtoReflect.Descriptor instead.
func (*SearchRegionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRegionsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchRegionsRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *SearchRegionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRegionsRequest) GetSort() *SortOptions {
	if x != nil {
		return x.Sort
	}
	return nil
}

type CreateRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegionRequest) Reset() {
	*x = CreateRegionRequest{}
	mi := &file_proto_location_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegionRequest) ProtoMessage() {}

func (x *CreateRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegionRequest.ProtoReflect.Descriptor instead.
func (*CreateRegionRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRegionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRegionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRegionRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type UpdateRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRegionRequest) Reset() {
	*x = UpdateRegionRequest{}
	mi := &file_proto_location_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegionRequest) ProtoMessage() {}

func (x *UpdateRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegionRequest.ProtoReflect.Descriptor instead.
func (*UpdateRegionRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRegionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRegionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRegionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateRegionRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type DeleteRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRegionRequest) Reset() {
	*x = DeleteRegionRequest{}
	mi := &file_proto_location_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRegionRequest) ProtoMessage() {}

func (x *DeleteRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRegionRequest.ProtoReflect.Descriptor instead.
func (*DeleteRegionRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRegionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RegionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionResponse) Reset() {
	*x = RegionResponse{}
	mi := &file_proto_location_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionResponse) ProtoMessage() {}

func (x *RegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionResponse.ProtoReflect.Descriptor instead.
func (*RegionResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{6}
}

func (x *RegionResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegionResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegionResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RegionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RegionResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetRegionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RegionResponse      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionsResponse) Reset() {
	*x = GetRegionsResponse{}
	mi := &file_proto_location_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionsResponse) ProtoMessage() {}

func (x *GetRegionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionsResponse.ProtoReflect.Descriptor instead.
func (*GetRegionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetRegionsResponse) GetItems() []*RegionResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetRegionsResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type RegionWithCitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *RegionResponse        `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Cities        []*CityResponse        `protobuf:"bytes,2,rep,name=cities,proto3" json:"cities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionWithCitiesResponse) Reset() {
	*x = RegionWithCitiesResponse{}
	mi := &file_proto_location_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionWithCitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionWithCitiesResponse) ProtoMessage() {}

func (x *RegionWithCitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionWithCitiesResponse.ProtoReflect.Descriptor instead.
func (*RegionWithCitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{8}
}

func (x *RegionWithCitiesResponse) GetRegion() *RegionResponse {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *RegionWithCitiesResponse) GetCities() []*CityResponse {
	if x != nil {
		return x.Cities
	}
	return nil
}

type GetCityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCityRequest) Reset() {
	*x = GetCityRequest{}
	mi := &file_proto_location_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCityRequest) ProtoMessage() {}

func (x *GetCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCityRequest.ProtoReflect.Descriptor instead.
func (*GetCityRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetCityRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCityBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCityBySlugRequest) Reset() {
	*x = GetCityBySlugRequest{}
	mi := &file_proto_location_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCityBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCityBySlugRequest) ProtoMessage() {}

func (x *GetCityBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCityBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetCityBySlugRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetCityBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetCitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          int32                  `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter        *CityFilter            `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Sort          *SortOptions           `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCitiesRequest) Reset() {
	*x = GetCitiesRequest{}
	mi := &file_proto_location_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCitiesRequest) ProtoMessage() {}

func (x *GetCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetCitiesRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetCitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCitiesRequest) GetFilter() *CityFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetCitiesRequest) GetSort() *SortOptions {
	if x != nil {
		return x.Sort
	}
	return nil
}

type GetCitiesByRegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint32                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Skip          int32                  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort          *SortOptions           `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCitiesByRegionRequest) Reset() {
	*x = GetCitiesByRegionRequest{}
	mi := &file_proto_location_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCitiesByRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCitiesByRegionRequest) ProtoMessage() {}

func (x *GetCitiesByRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCitiesByRegionRequest.ProtoReflect.Descriptor instead.
func (*GetCitiesByRegionRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetCitiesByRegionRequest) GetRegionId() uint32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *GetCitiesByRegionRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetCitiesByRegionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCitiesByRegionRequest) GetSort() *SortOptions {
	if x != nil {
		return x.Sort
	}
	return nil
}

type SearchCitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	RegionId      *uint32                `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3,oneof" json:"region_id,omitempty"`
	Skip          int32                  `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort          *SortOptions           `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCitiesRequest) Reset() {
	*x = SearchCitiesRequest{}
	mi := &file_proto_location_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCitiesRequest) ProtoMessage() {}

func (x *SearchCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCitiesRequest.ProtoReflect.Descriptor instead.
func (*SearchCitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{13}
}

func (x *SearchCitiesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchCitiesRequest) GetRegionId() uint32 {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return 0
}

func (x *SearchCitiesRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *SearchCitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchCitiesRequest) GetSort() *SortOptions {
	if x != nil {
		return x.Sort
	}
	return nil
}

type GetLargestCitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort          *SortOptions           `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLargestCitiesRequest) Reset() {
	*x = GetLargestCitiesRequest{}
	mi := &file_proto_location_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLargestCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLargestCitiesRequest) ProtoMessage() {}

func (x *GetLargestCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLargestCitiesRequest.ProtoReflect.Descriptor instead.
func (*GetLargestCitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetLargestCitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLargestCitiesRequest) GetSort() *SortOptions {
	if x != nil {
		return x.Sort
	}
	return nil
}

type CreateCityRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RegionId         uint32                 `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Population       int32                  `protobuf:"varint,3,opt,name=population,proto3" json:"population,omitempty"`
	IsRegionalCenter bool                   `protobuf:"varint,4,opt,name=is_regional_center,json=isRegionalCenter,proto3" json:"is_regional_center,omitempty"`
	Latitude         float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Slug             string                 `protobuf:"bytes,7,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateCityRequest) Reset() {
	*x = CreateCityRequest{}
	mi := &file_proto_location_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCityRequest) ProtoMessage() {}

func (x *CreateCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCityRequest.ProtoReflect.Descriptor instead.
func (*CreateCityRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCityRequest) GetRegionId() uint32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *CreateCityRequest) GetPopulation() int32 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *CreateCityRequest) GetIsRegionalCenter() bool {
	if x != nil {
		return x.IsRegionalCenter
	}
	return false
}

func (x *CreateCityRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateCityRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateCityRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type UpdateCityRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	RegionId         *uint32                `protobuf:"varint,3,opt,name=region_id,json=regionId,proto3,oneof" json:"region_id,omitempty"`
	Population       *int32                 `protobuf:"varint,4,opt,name=population,proto3,oneof" json:"population,omitempty"`
	IsRegionalCenter *bool                  `protobuf:"varint,5,opt,name=is_regional_center,json=isRegionalCenter,proto3,oneof" json:"is_regional_center,omitempty"`
	Latitude         *float64               `protobuf:"fixed64,6,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude        *float64               `protobuf:"fixed64,7,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	Slug             *string                `protobuf:"bytes,8,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateCityRequest) Reset() {
	*x = UpdateCityRequest{}
	mi := &file_proto_location_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCityRequest) ProtoMessage() {}

func (x *UpdateCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCityRequest.ProtoReflect.Descriptor instead.
func (*UpdateCityRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCityRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCityRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCityRequest) GetRegionId() uint32 {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return 0
}

func (x *UpdateCityRequest) GetPopulation() int32 {
	if x != nil && x.Population != nil {
		return *x.Population
	}
	return 0
}

func (x *UpdateCityRequest) GetIsRegionalCenter() bool {
	if x != nil && x.IsRegionalCenter != nil {
		return *x.IsRegionalCenter
	}
	return false
}

func (x *UpdateCityRequest) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *UpdateCityRequest) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *UpdateCityRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

type DeleteCityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCityRequest) Reset() {
	*x = DeleteCityRequest{}
	mi := &file_proto_location_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCityRequest) ProtoMessage() {}

func (x *DeleteCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCityRequest.ProtoReflect.Descriptor instead.
func (*DeleteCityRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteCityRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CityResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RegionId         uint32                 `protobuf:"varint,3,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Population       int32                  `protobuf:"varint,4,opt,name=population,proto3" json:"population,omitempty"`
	IsRegionalCenter bool                   `protobuf:"varint,5,opt,name=is_regional_center,json=isRegionalCenter,proto3" json:"is_regional_center,omitempty"`
	Latitude         float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Region           *RegionResponse        `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	Slug             string                 `protobuf:"bytes,11,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CityResponse) Reset() {
	*x = CityResponse{}
	mi := &file_proto_location_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityResponse) ProtoMessage() {}

func (x *CityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityResponse.ProtoReflect.Descriptor instead.
func (*CityResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{18}
}

func (x *CityResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CityResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CityResponse) GetRegionId() uint32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *CityResponse) GetPopulation() int32 {
	if x != nil {
		return x.Population
	}
	return 0
}

func (x *CityResponse) GetIsRegionalCenter() bool {
	if x != nil {
		return x.IsRegionalCenter
	}
	return false
}

func (x *CityResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CityResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CityResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CityResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CityResponse) GetRegion() *RegionResponse {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *CityResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CityWithRegionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          *CityResponse          `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Region        *RegionResponse        `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityWithRegionResponse) Reset() {
	*x = CityWithRegionResponse{}
	mi := &file_proto_location_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityWithRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityWithRegionResponse) ProtoMessage() {}

func (x *CityWithRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityWithRegionResponse.ProtoReflect.Descriptor instead.
func (*CityWithRegionResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{19}
}

func (x *CityWithRegionResponse) GetCity() *CityResponse {
	if x != nil {
		return x.City
	}
	return nil
}

func (x *CityWithRegionResponse) GetRegion() *RegionResponse {
	if x != nil {
		return x.Region
	}
	return nil
}

type GetCitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CityResponse        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *PaginationResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCitiesResponse) Reset() {
	*x = GetCitiesResponse{}
	mi := &file_proto_location_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCitiesResponse) ProtoMessage() {}

func (x *GetCitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetCitiesResponse) GetItems() []*CityResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCitiesResponse) GetPagination() *PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CityFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	RegionId      *uint32                `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3,oneof" json:"region_id,omitempty"`
	PopulationMin *int32                 `protobuf:"varint,3,opt,name=population_min,json=populationMin,proto3,oneof" json:"population_min,omitempty"`
	PopulationMax *int32                 `protobuf:"varint,4,opt,name=population_max,json=populationMax,proto3,oneof" json:"population_max,omitempty"`
	Ids           []uint32               `protobuf:"varint,5,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Slug          *string                `protobuf:"bytes,6,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityFilter) Reset() {
	*x = CityFilter{}
	mi := &file_proto_location_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityFilter) ProtoMessage() {}

func (x *CityFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityFilter.ProtoReflect.Descriptor instead.
func (*CityFilter) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{21}
}

func (x *CityFilter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CityFilter) GetRegionId() uint32 {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return 0
}

func (x *CityFilter) GetPopulationMin() int32 {
	if x != nil && x.PopulationMin != nil {
		return *x.PopulationMin
	}
	return 0
}

func (x *CityFilter) GetPopulationMax() int32 {
	if x != nil && x.PopulationMax != nil {
		return *x.PopulationMax
	}
	return 0
}

func (x *CityFilter) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *CityFilter) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

type GetMostSearchedQueriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMostSearchedQueriesRequest) Reset() {
	*x = GetMostSearchedQueriesRequest{}
	mi := &file_proto_location_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMostSearchedQueriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMostSearchedQueriesRequest) ProtoMessage() {}

func (x *GetMostSearchedQueriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMostSearchedQueriesRequest.ProtoReflect.Descriptor instead.
func (*GetMostSearchedQueriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetMostSearchedQueriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MostSearchedQueriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SearchQueryCount    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MostSearchedQueriesResponse) Reset() {
	*x = MostSearchedQueriesResponse{}
	mi := &file_proto_location_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MostSearchedQueriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostSearchedQueriesResponse) ProtoMessage() {}

func (x *MostSearchedQueriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostSearchedQueriesResponse.ProtoReflect.Descriptor instead.
func (*MostSearchedQueriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{23}
}

func (x *MostSearchedQueriesResponse) GetItems() []*SearchQueryCount {
	if x != nil {
		return x.Items
	}
	return nil
}

type SearchQueryCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchQueryCount) Reset() {
	*x = SearchQueryCount{}
	mi := &file_proto_location_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQueryCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQueryCount) ProtoMessage() {}

func (x *SearchQueryCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQueryCount.ProtoReflect.Descriptor instead.
func (*SearchQueryCount) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{24}
}

func (x *SearchQueryCount) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchQueryCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SearchStatsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalSearches       int64                  `protobuf:"varint,1,opt,name=total_searches,json=totalSearches,proto3" json:"total_searches,omitempty"`
	FoundSearches       int64                  `protobuf:"varint,2,opt,name=found_searches,json=foundSearches,proto3" json:"found_searches,omitempty"`
	SuccessRate         float64                `protobuf:"fixed64,3,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AvgProcessingTimeMs float64                `protobuf:"fixed64,4,opt,name=avg_processing_time_ms,json=avgProcessingTimeMs,proto3" json:"avg_processing_time_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SearchStatsResponse) Reset() {
	*x = SearchStatsResponse{}
	mi := &file_proto_location_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStatsResponse) ProtoMessage() {}

func (x *SearchStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStatsResponse.ProtoReflect.Descriptor instead.
func (*SearchStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{25}
}

func (x *SearchStatsResponse) GetTotalSearches() int64 {
	if x != nil {
		return x.TotalSearches
	}
	return 0
}

func (x *SearchStatsResponse) GetFoundSearches() int64 {
	if x != nil {
		return x.FoundSearches
	}
	return 0
}

func (x *SearchStatsResponse) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *SearchStatsResponse) GetAvgProcessingTimeMs() float64 {
	if x != nil {
		return x.AvgProcessingTimeMs
	}
	return 0
}

type SortOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"` // Поле для сортировки: id, name, created_at, updated_at, population
	Order         string                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"` // Порядок: asc, desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortOptions) Reset() {
	*x = SortOptions{}
	mi := &file_proto_location_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortOptions) ProtoMessage() {}

func (x *SortOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortOptions.ProtoReflect.Descriptor instead.
func (*SortOptions) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{26}
}

func (x *SortOptions) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortOptions) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Pages         int32                  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_proto_location_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_service_proto_rawDescGZIP(), []int{27}
}

func (x *PaginationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PaginationResponse) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

var File_proto_location_service_proto protoreflect.FileDescriptor

const file_proto_location_service_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/location_service.proto\x12\blocation\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n" +
	"\x10GetRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"h\n" +
	"\x11GetRegionsRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12)\n" +
	"\x04sort\x18\x03 \x01(\v2\x15.location.SortOptionsR\x04sort\"\x85\x01\n" +
	"\x14SearchRegionsRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12)\n" +
	"\x04sort\x18\x04 \x01(\v2\x15.location.SortOptionsR\x04sort\"W\n" +
	"\x13CreateRegionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\"g\n" +
	"\x13UpdateRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\"%\n" +
	"\x13DeleteRegionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xd8\x01\n" +
	"\x0eRegionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x82\x01\n" +
	"\x12GetRegionsResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.location.RegionResponseR\x05items\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.location.PaginationResponseR\n" +
	"pagination\"|\n" +
	"\x18RegionWithCitiesResponse\x120\n" +
	"\x06region\x18\x01 \x01(\v2\x18.location.RegionResponseR\x06region\x12.\n" +
	"\x06cities\x18\x02 \x03(\v2\x16.location.CityResponseR\x06cities\" \n" +
	"\x0eGetCityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"*\n" +
	"\x14GetCityBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\x95\x01\n" +
	"\x10GetCitiesRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12,\n" +
	"\x06filter\x18\x03 \x01(\v2\x14.location.CityFilterR\x06filter\x12)\n" +
	"\x04sort\x18\x04 \x01(\v2\x15.location.SortOptionsR\x04sort\"\x8c\x01\n" +
	"\x18GetCitiesByRegionRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\rR\bregionId\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12)\n" +
	"\x04sort\x18\x04 \x01(\v2\x15.location.SortOptionsR\x04sort\"\xb4\x01\n" +
	"\x13SearchCitiesRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12 \n" +
	"\tregion_id\x18\x02 \x01(\rH\x00R\bregionId\x88\x01\x01\x12\x12\n" +
	"\x04skip\x18\x03 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12)\n" +
	"\x04sort\x18\x05 \x01(\v2\x15.location.SortOptionsR\x04sortB\f\n" +
	"\n" +
	"_region_id\"Z\n" +
	"\x17GetLargestCitiesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12)\n" +
	"\x04sort\x18\x02 \x01(\v2\x15.location.SortOptionsR\x04sort\"\xe0\x01\n" +
	"\x11CreateCityRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\rR\bregionId\x12\x1e\n" +
	"\n" +
	"population\x18\x03 \x01(\x05R\n" +
	"population\x12,\n" +
	"\x12is_regional_center\x18\x04 \x01(\bR\x10isRegionalCenter\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04slug\x18\a \x01(\tR\x04slug\"\xf4\x02\n" +
	"\x11UpdateCityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12 \n" +
	"\tregion_id\x18\x03 \x01(\rH\x01R\bregionId\x88\x01\x01\x12#\n" +
	"\n" +
	"population\x18\x04 \x01(\x05H\x02R\n" +
	"population\x88\x01\x01\x121\n" +
	"\x12is_regional_center\x18\x05 \x01(\bH\x03R\x10isRegionalCenter\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\x06 \x01(\x01H\x04R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\a \x01(\x01H\x05R\tlongitude\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\b \x01(\tH\x06R\x04slug\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_region_idB\r\n" +
	"\v_populationB\x15\n" +
	"\x13_is_regional_centerB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\a\n" +
	"\x05_slug\"#\n" +
	"\x11DeleteCityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x93\x03\n" +
	"\fCityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tregion_id\x18\x03 \x01(\rR\bregionId\x12\x1e\n" +
	"\n" +
	"population\x18\x04 \x01(\x05R\n" +
	"population\x12,\n" +
	"\x12is_regional_center\x18\x05 \x01(\bR\x10isRegionalCenter\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x120\n" +
	"\x06region\x18\n" +
	" \x01(\v2\x18.location.RegionResponseR\x06region\x12\x12\n" +
	"\x04slug\x18\v \x01(\tR\x04slug\"v\n" +
	"\x16CityWithRegionResponse\x12*\n" +
	"\x04city\x18\x01 \x01(\v2\x16.location.CityResponseR\x04city\x120\n" +
	"\x06region\x18\x02 \x01(\v2\x18.location.RegionResponseR\x06region\"\x7f\n" +
	"\x11GetCitiesResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.location.CityResponseR\x05items\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.location.PaginationResponseR\n" +
	"pagination\"\x90\x02\n" +
	"\n" +
	"CityFilter\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12 \n" +
	"\tregion_id\x18\x02 \x01(\rH\x01R\bregionId\x88\x01\x01\x12*\n" +
	"\x0epopulation_min\x18\x03 \x01(\x05H\x02R\rpopulationMin\x88\x01\x01\x12*\n" +
	"\x0epopulation_max\x18\x04 \x01(\x05H\x03R\rpopulationMax\x88\x01\x01\x12\x10\n" +
	"\x03ids\x18\x05 \x03(\rR\x03ids\x12\x17\n" +
	"\x04slug\x18\x06 \x01(\tH\x04R\x04slug\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_region_idB\x11\n" +
	"\x0f_population_minB\x11\n" +
	"\x0f_population_maxB\a\n" +
	"\x05_slug\"5\n" +
	"\x1dGetMostSearchedQueriesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"O\n" +
	"\x1bMostSearchedQueriesResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.location.SearchQueryCountR\x05items\">\n" +
	"\x10SearchQueryCount\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xbb\x01\n" +
	"\x13SearchStatsResponse\x12%\n" +
	"\x0etotal_searches\x18\x01 \x01(\x03R\rtotalSearches\x12%\n" +
	"\x0efound_searches\x18\x02 \x01(\x03R\rfoundSearches\x12!\n" +
	"\fsuccess_rate\x18\x03 \x01(\x01R\vsuccessRate\x123\n" +
	"\x16avg_processing_time_ms\x18\x04 \x01(\x01R\x13avgProcessingTimeMs\"9\n" +
	"\vSortOptions\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\"h\n" +
	"\x12PaginationResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x05R\x05pages2\x94\b\n" +
	"\x0fLocationService\x12A\n" +
	"\tGetRegion\x12\x1a.location.GetRegionRequest\x1a\x18.location.RegionResponse\x12G\n" +
	"\n" +
	"GetRegions\x12\x1b.location.GetRegionsRequest\x1a\x1c.location.GetRegionsResponse\x12G\n" +
	"\fCreateRegion\x12\x1d.location.CreateRegionRequest\x1a\x18.location.RegionResponse\x12G\n" +
	"\fUpdateRegion\x12\x1d.location.UpdateRegionRequest\x1a\x18.location.RegionResponse\x12G\n" +
	"\fDeleteRegion\x12\x1d.location.DeleteRegionRequest\x1a\x18.location.RegionResponse\x12;\n" +
	"\aGetCity\x12\x18.location.GetCityRequest\x1a\x16.location.CityResponse\x12G\n" +
	"\rGetCityBySlug\x12\x1e.location.GetCityBySlugRequest\x1a\x16.location.CityResponse\x12D\n" +
	"\tGetCities\x12\x1a.location.GetCitiesRequest\x1a\x1b.location.GetCitiesResponse\x12R\n" +
	"\x10GetLargestCities\x12!.location.GetLargestCitiesRequest\x1a\x1b.location.GetCitiesResponse\x12A\n" +
	"\n" +
	"CreateCity\x12\x1b.location.CreateCityRequest\x1a\x16.location.CityResponse\x12A\n" +
	"\n" +
	"UpdateCity\x12\x1b.location.UpdateCityRequest\x1a\x16.location.CityResponse\x12A\n" +
	"\n" +
	"DeleteCity\x12\x1b.location.DeleteCityRequest\x1a\x16.location.CityResponse\x12G\n" +
	"\x0eGetSearchStats\x12\x16.google.protobuf.Empty\x1a\x1d.location.SearchStatsResponse\x12h\n" +
	"\x16GetMostSearchedQueries\x12'.location.GetMostSearchedQueriesRequest\x1a%.location.MostSearchedQueriesResponseB\x1fZ\x1dlocation-service-go/pkg/protob\x06proto3"

var (
	file_proto_location_service_proto_rawDescOnce sync.Once
	file_proto_location_service_proto_rawDescData []byte
)

func file_proto_location_service_proto_rawDescGZIP() []byte {
	file_proto_location_service_proto_rawDescOnce.Do(func() {
		file_proto_location_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_location_service_proto_rawDesc), len(file_proto_location_service_proto_rawDesc)))
	})
	return file_proto_location_service_proto_rawDescData
}

var file_proto_location_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_location_service_proto_goTypes = []any{
	(*GetRegionRequest)(nil),              // 0: location.GetRegionRequest
	(*GetRegionsRequest)(nil),             // 1: location.GetRegionsRequest
	(*SearchRegionsRequest)(nil),          // 2: location.SearchRegionsRequest
	(*CreateRegionRequest)(nil),           // 3: location.CreateRegionRequest
	(*UpdateRegionRequest)(nil),           // 4: location.UpdateRegionRequest
	(*DeleteRegionRequest)(nil),           // 5: location.DeleteRegionRequest
	(*RegionResponse)(nil),                // 6: location.RegionResponse
	(*GetRegionsResponse)(nil),            // 7: location.GetRegionsResponse
	(*RegionWithCitiesResponse)(nil),      // 8: location.RegionWithCitiesResponse
	(*GetCityRequest)(nil),                // 9: location.GetCityRequest
	(*GetCityBySlugRequest)(nil),          // 10: location.GetCityBySlugRequest
	(*GetCitiesRequest)(nil),              // 11: location.GetCitiesRequest
	(*GetCitiesByRegionRequest)(nil),      // 12: location.GetCitiesByRegionRequest
	(*SearchCitiesRequest)(nil),           // 13: location.SearchCitiesRequest
	(*GetLargestCitiesRequest)(nil),       // 14: location.GetLargestCitiesRequest
	(*CreateCityRequest)(nil),             // 15: location.CreateCityRequest
	(*UpdateCityRequest)(nil),             // 16: location.UpdateCityRequest
	(*DeleteCityRequest)(nil),             // 17: location.DeleteCityRequest
	(*CityResponse)(nil),                  // 18: location.CityResponse
	(*CityWithRegionResponse)(nil),        // 19: location.CityWithRegionResponse
	(*GetCitiesResponse)(nil),             // 20: location.GetCitiesResponse
	(*CityFilter)(nil),                    // 21: location.CityFilter
	(*GetMostSearchedQueriesRequest)(nil), // 22: location.GetMostSearchedQueriesRequest
	(*MostSearchedQueriesResponse)(nil),   // 23: location.MostSearchedQueriesResponse
	(*SearchQueryCount)(nil),              // 24: location.SearchQueryCount
	(*SearchStatsResponse)(nil),           // 25: location.SearchStatsResponse
	(*SortOptions)(nil),                   // 26: location.SortOptions
	(*PaginationResponse)(nil),            // 27: location.PaginationResponse
	(*timestamppb.Timestamp)(nil),         // 28: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 29: google.protobuf.Empty
}
var file_proto_location_service_proto_depIdxs = []int32{
	26, // 0: location.GetRegionsRequest.sort:type_name -> location.SortOptions
	26, // 1: location.SearchRegionsRequest.sort:type_name -> location.SortOptions
	28, // 2: location.RegionResponse.created_at:type_name -> google.protobuf.Timestamp
	28, // 3: location.RegionResponse.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 4: location.GetRegionsResponse.items:type_name -> location.RegionResponse
	27, // 5: location.GetRegionsResponse.pagination:type_name -> location.PaginationResponse
	6,  // 6: location.RegionWithCitiesResponse.region:type_name -> location.RegionResponse
	18, // 7: location.RegionWithCitiesResponse.cities:type_name -> location.CityResponse
	21, // 8: location.GetCitiesRequest.filter:type_name -> location.CityFilter
	26, // 9: location.GetCitiesRequest.sort:type_name -> location.SortOptions
	26, // 10: location.GetCitiesByRegionRequest.sort:type_name -> location.SortOptions
	26, // 11: location.SearchCitiesRequest.sort:type_name -> location.SortOptions
	26, // 12: location.GetLargestCitiesRequest.sort:type_name -> location.SortOptions
	28, // 13: location.CityResponse.created_at:type_name -> google.protobuf.Timestamp
	28, // 14: location.CityResponse.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 15: location.CityResponse.region:type_name -> location.RegionResponse
	18, // 16: location.CityWithRegionResponse.city:type_name -> location.CityResponse
	6,  // 17: location.CityWithRegionResponse.region:type_name -> location.RegionResponse
	18, // 18: location.GetCitiesResponse.items:type_name -> location.CityResponse
	27, // 19: location.GetCitiesResponse.pagination:type_name -> location.PaginationResponse
	24, // 20: location.MostSearchedQueriesResponse.items:type_name -> location.SearchQueryCount
	0,  // 21: location.LocationService.GetRegion:input_type -> location.GetRegionRequest
	1,  // 22: location.LocationService.GetRegions:input_type -> location.GetRegionsRequest
	3,  // 23: location.LocationService.CreateRegion:input_type -> location.CreateRegionRequest
	4,  // 24: location.LocationService.UpdateRegion:input_type -> location.UpdateRegionRequest
	5,  // 25: location.LocationService.DeleteRegion:input_type -> location.DeleteRegionRequest
	9,  // 26: location.LocationService.GetCity:input_type -> location.GetCityRequest
	10, // 27: location.LocationService.GetCityBySlug:input_type -> location.GetCityBySlugRequest
	11, // 28: location.LocationService.GetCities:input_type -> location.GetCitiesRequest
	14, // 29: location.LocationService.GetLargestCities:input_type -> location.GetLargestCitiesRequest
	15, // 30: location.LocationService.CreateCity:input_type -> location.CreateCityRequest
	16, // 31: location.LocationService.UpdateCity:input_type -> location.UpdateCityRequest
	17, // 32: location.LocationService.DeleteCity:input_type -> location.DeleteCityRequest
	29, // 33: location.LocationService.GetSearchStats:input_type -> google.protobuf.Empty
	22, // 34: location.LocationService.GetMostSearchedQueries:input_type -> location.GetMostSearchedQueriesRequest
	6,  // 35: location.LocationService.GetRegion:output_type -> location.RegionResponse
	7,  // 36: location.LocationService.GetRegions:output_type -> location.GetRegionsResponse
	6,  // 37: location.LocationService.CreateRegion:output_type -> location.RegionResponse
	6,  // 38: location.LocationService.UpdateRegion:output_type -> location.RegionResponse
	6,  // 39: location.LocationService.DeleteRegion:output_type -> location.RegionResponse
	18, // 40: location.LocationService.GetCity:output_type -> location.CityResponse
	18, // 41: location.LocationService.GetCityBySlug:output_type -> location.CityResponse
	20, // 42: location.LocationService.GetCities:output_type -> location.GetCitiesResponse
	20, // 43: location.LocationService.GetLargestCities:output_type -> location.GetCitiesResponse
	18, // 44: location.LocationService.CreateCity:output_type -> location.CityResponse
	18, // 45: location.LocationService.UpdateCity:output_type -> location.CityResponse
	18, // 46: location.LocationService.DeleteCity:output_type -> location.CityResponse
	25, // 47: location.LocationService.GetSearchStats:output_type -> location.SearchStatsResponse
	23, // 48: location.LocationService.GetMostSearchedQueries:output_type -> location.MostSearchedQueriesResponse
	35, // [35:49] is the sub-list for method output_type
	21, // [21:35] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_location_service_proto_init() }
func file_proto_location_service_proto_init() {
	if File_proto_location_service_proto != nil {
		return
	}
	file_proto_location_service_proto_msgTypes[13].OneofWrappers = []any{}
	file_proto_location_service_proto_msgTypes[16].OneofWrappers = []any{}
	file_proto_location_service_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_location_service_proto_rawDesc), len(file_proto_location_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_location_service_proto_goTypes,
		DependencyIndexes: file_proto_location_service_proto_depIdxs,
		MessageInfos:      file_proto_location_service_proto_msgTypes,
	}.Build()
	File_proto_location_service_proto = out.File
	file_proto_location_service_proto_goTypes = nil
	file_proto_location_service_proto_depIdxs = nil
}
